name: HopeCraft
main: org.hopestudio.hopeCraft.HopeCraft
version: 1.6.9
api-version: "1.21"
commands:
  hopecraft:
    description: 打开HopeCraft主菜单
    usage: /hopecraft
  skull:
    description: 获取玩家头颅
    usage: /skull [玩家名]
  birthday:
    description: 生日相关命令
    usage: /birthday <set|confirm|broadcast>

  motd:
    description: 修改服务器MOTD（每日消息）
    usage: /motd [新内容]
permissions:
  hopecraft.admin:
    description: HopeCraft管理员权限
    default: op  # 仅OP默认拥有此权限
    # 明确MOTD权限继承关系
    children:
      hopecraft.motd: true

  hopecraft.motd:
    description: 允许修改服务器MOTD
    default: false  # 默认关闭，需通过hopecraft.admin继承或单独分配